env:
  global:
    - ANDROID_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=22.0.1
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_EMULATOR="Google Inc.:Google APIs:22"

sudo: false
jdk: oraclejdk7
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Google APIs
    - addon-google_apis-google-22

    # Additional components
    - extra-google-gcm
    - extra-google-google_play_services

    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

    # Support library
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL

before_script:
 - chmod +x gradlew
 # Create and start emulator
 - android list targets
 - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:22" --abi google_apis/armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &

script:
 # - ./wait_for_emulator
 # - ./gradlew connectedAndroidTest
